### ISSUE TITLE
Font name and styles.

### ISSUE THREAD

**Issue by sowizz** [li-vu/st-match#1]
Hi,

I am sorry that I'm posting this as an issue. What kind of font you use? How one can achieve that font style that is visible in keywords such as class and if? I guess your syntax theme set those to italics and the font has italics in such style, right?

**Comment by li-vu** [comment]
Hi,

Thank you for your question! The font that I used in the screenshots is Operator Mono. It's not the font style that set the italic keywords, but the Material Theme that I used. You may like to check that theme out.
